### ISSUE TITLE
Deploying trader for Decision Tree and Random Forest

### ISSUE THREAD

**Issue by t3ch9** [paulo-al-castro/mt5se#1]
Hello, thank you for sharing this project. I would like to test with different machine learning frameworks.

Are there any examples or notebooks available for deploying a trader for operation on real (or simulated ) accounts with Decision Tree and Random Forest?

**Comment by paulo-al-castro** [comment]
Hi t3ch9, Thank you for your interest in mt5se project and sorry for the late answer.

Yes, you can find examples using Decision Tree and Random Forest in: https://paulo-al-castro.github.io/mt5se/ai_mt5se.html
You may also find another examples in : https://paulo-al-castro.github.io/mt5se/
